apiVersion: v1
kind: Pod
metadata:
  name: mongo1
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - name: nodejs-port
      containerPort: 27017
    env:
      - name: GET_HOSTS_FROM
        value: dns

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: mongo